variables:
  IMAGE_BASIC: "alpine-ocaml"

stages:
  - configure
  - build
  - bootstrap
  - test

docker-images:
  stage: configure
  image: quay.io/buildah/stable
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # Write all image metadata in the docker format, not the standard OCI format.
    # Newer versions of docker can handle the OCI format, but older versions, like
    # the one shipped with Fedora 30, cannot handle the format.
    BUILDAH_FORMAT: docker
    # You may need this workaround for some errors: https://stackoverflow.com/a/70438141/1233435
    BUILDAH_ISOLATION: chroot
  before_script:
    # Log in to the GitLab container registry
    - export REGISTRY_AUTH_FILE=$HOME/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah images
    - buildah build -f $IMAGE_BASIC -t $CI_REGISTRY_IMAGE/$IMAGE_BASIC
    - buildah images
    - buildah push $CI_REGISTRY_IMAGE/$IMAGE_BASIC
  only:
    changes:
    - $IMAGE_BASIC

check-config:
  stage: build
  image: $CI_REGISTRY_IMAGE/$IMAGE_BASIC
  script:
    - uname -a
    - ocaml -version
    
build-init:
  stage: build
  image: $CI_REGISTRY_IMAGE/$IMAGE_BASIC
  script:
    - sh make.sh
  artifacts:
    paths:
      - lepton.bin

build-bootstrap:
  stage: bootstrap
  image: $CI_REGISTRY_IMAGE/$IMAGE_BASIC
  script:
    - cd bootstrap

    # Run lepton on lepton.nw
    - ../lepton.bin lepton.nw -o lepton.tex
    
    # Assert generated files. (source files for compilation)
    - diff make.sh          ../make.sh
    - diff lexer.mll        ../lexer.mll
    - diff formatters.ml    ../formatters.ml
    - diff interpreters.ml  ../interpreters.ml
    - diff lepton.ml        ../lepton.ml
    - diff main.ml          ../main.ml
    
    # Assert generated files. (gitlab CI + licence)
    - diff .gitlab-ci.yml   ../.gitlab-ci.yml
    - diff Licence_CeCILL_V2.1-en.txt ../Licence_CeCILL_V2.1-en.txt
    
     # Assert generated files. (LaTeX files)
    - diff lepton.sty ../lepton.sty
    - diff biblio_lepton.bib ../biblio_lepton.bib

test-examples:
  stage: test
  image: $CI_REGISTRY_IMAGE/$IMAGE_BASIC
  script:
    - cd examples
    - ../lepton.bin -format_with tex hello.nw -o hello.tex
    - diff hello.tex hello.tex.expected
    - ../lepton.bin lepton_test.nw -o lepton_test.tex
    - diff lepton_test.tex lepton_test.tex.expected
    - ../lepton.bin -format_with github github-formatter.nw -o github-formatter.md
    - diff github-formatter.md github-formatter.md.expected

